modLoader="javafml"
loaderVersion="[40,)"
license="The Unlicense"

[[mods]]
    modId="minema"
    version="${file.jarVersion}"
    displayName="Minema"
    displayURL="https://github.com/daipenger/minema"
    authors="Barracuda, Gregosteros"
    description='''This mod allows you to record fluid movies in Minecraft, even if the video recording itself is not.'''